// Generated by backend/tools/export_contract.py; response defaults are always serialized.
export type BlindPoint = {
  category: "market" | "supermarket" | "pharmacy" | "hospital_pharmacy" | "school";
  major_category: "shopping" | "medical" | "education";
  minor_category: "market" | "supermarket" | "pharmacy" | "hospital_pharmacy" | "school";
  location: Origin;
  status: "covered" | "blind" | "unknown";
  evidence: string;
};

export type CategoryResult = {
  category: "market" | "supermarket" | "pharmacy" | "hospital_pharmacy" | "school";
  major_category: "shopping" | "medical" | "education";
  minor_category: "market" | "supermarket" | "pharmacy" | "hospital_pharmacy" | "school";
  query_status: "complete" | "unknown" | "failed";
  count_in_circle: number | null;
  service_status: "covered" | "blind" | "unknown";
};

export type Data = {
  geometry: Geometry | null;
  evidenceGeometry: Geometry | null;
  inferredRegion: Geometry | null;
  uncertain_region: Geometry | null;
  unknown_region: Geometry | null;
  computation_extent: Geometry | null;
  facilities: Array<Facility> | null;
  categories: Array<CategoryResult>;
  blind_points: Array<BlindPoint> | null;
  blind_region: Geometry | null;
  report: string | null;
};

export type DistanceRule = {
  metric: "unconfirmed" | "straight_line" | "walking_route";
  threshold_m: number;
  inclusive: boolean | null;
  tolerance_m: number | null;
  assessment_scope: "unconfirmed" | "isochrone" | "community" | "sample";
  category_policy: "unconfirmed" | "per_category" | "major_minor";
};

export type Facility = {
  category: "market" | "supermarket" | "pharmacy" | "hospital_pharmacy" | "school";
  major_category: "shopping" | "medical" | "education";
  minor_category: "market" | "supermarket" | "pharmacy" | "hospital_pharmacy" | "school";
  id: string;
  name: string;
  location: Origin;
  in_circle: boolean | null;
  poiEvidence?: PoiEvidence | null;
};

export type Geometry = {
  type: "Polygon" | "MultiPolygon";
  coordinates: Array<unknown>;
  coordinateSystem: "bd09ll";
};

export type Issue = {
  code: string;
  message: string;
  scope: string;
  severity: "warning" | "error" | "pending";
};

export type Origin = {
  lng: number;
  lat: number;
};

export type PoiEvidence = {
  version: "1.0";
  facilityId: string;
  status: "pending" | "verified_reachable" | "verified_unreachable";
  reason: string | null;
  duration: number | null;
  observedDuration: number | null;
  endpointVerified: boolean;
  requestOrigin: [number, number];
  destination: [number, number];
  routeOrigin: [number, number] | null;
  routeDestination: [number, number] | null;
  originOffsetM: number | null;
  destinationOffsetM: number | null;
};

export type Rules = {
  version: string;
  time_threshold_s: 900;
  time_inclusive: true;
  time_tolerance_s: number;
  time_confirmation: "implementation_only" | "mock_only" | "baidu_sampled";
  distance: DistanceRule;
};

export type AnalysisResponse = {
  schema_version: "1.0";
  analysis_id: string;
  generated_at: string;
  status: "complete" | "partial" | "failed" | "empty";
  source: "mock" | "synthetic" | "system";
  algorithm_version: string | null;
  data_updated_at: string | null;
  origin: Origin | null;
  coordinate_system: "bd09ll";
  coordinate_order: "longitude,latitude";
  units: Record<string, string>;
  rules: Rules;
  data: Data;
  algorithm: Record<string, unknown> | null;
  warnings: Array<Issue>;
  errors: Array<Issue>;
};

export type TaskStatusResponse = {
  schema_version: "1.0";
  responseType: "task";
  taskId: string;
  status: "running" | "cancelling" | "completed" | "cancelled" | "failed";
  businessStatus: "complete" | "partial" | "failed" | "empty" | null;
  stage: string;
  requests: number;
  networkRequests: number;
  budget: number;
  elapsedSeconds: number;
  dataSource: "synthetic" | "baidu_walking";
  error: string | null;
};

export type AssessmentPoint = {
  location: Origin;
  duration_s: number;
  categories: Array<CoverageEvidence>;
};

export type CoverageEvidence = {
  category: "shopping" | "medical" | "education";
  status: "covered" | "blind" | "unknown";
  facility_id: string | null;
  distance_m: number | null;
  reason: string;
};

export type FacilityAnalysis = {
  status: "complete" | "partial" | "failed";
  queries: Array<QueryEvidence>;
  assessments: Array<AssessmentPoint>;
  candidate_points: number;
  assessed_points: number;
  unassessed_points: number;
  network_requests: number;
  elapsed_seconds: number;
  search_radius_m: number;
  routes: Record<string, RouteEvidence>;
  serviceBlindRegions: Record<string, Geometry>;
  warnings: Array<string>;
};

export type QueryEvidence = {
  category: "market" | "supermarket" | "pharmacy" | "hospital_pharmacy" | "school";
  query: string;
  status: "complete" | "partial" | "failed" | "truncated";
  pages: number;
  returned: number;
  excluded: number;
  invalid: number;
  total: number | null;
  reason: string | null;
};

export type RouteEvidence = {
  distance_m: number | null;
  duration_s: number | null;
  endpoint_verified: boolean;
  reason: string | null;
  path: Array<Array<number>>;
  poiEvidence?: PoiEvidence | null;
};

export type TaskResultResponse = {
  schema_version: "1.0";
  responseType: "result";
  taskId: string;
  taskStatus: "completed";
  status: "complete" | "partial" | "failed" | "empty";
  businessStatus: "complete" | "partial" | "failed" | "empty";
  dataSource: "synthetic" | "baidu_walking";
  center: Origin;
  generatedAt: number;
  facilitiesStatus: "not_integrated" | "complete" | "partial" | "failed";
  facilityAnalysis: FacilityAnalysis | null;
  coordinateSystem: "bd09ll";
  coordinateOrder: "longitude,latitude";
  units: Record<string, string>;
  rules: Rules;
  data: Data;
  algorithm: Record<string, unknown> | null;
  warnings: Array<Issue>;
  errors: Array<Issue>;
  isochrone: Record<string, unknown>;
};

export type OsmOfflineRequest = {
  origin: Origin;
  coordinate_system: "bd09ll";
  algorithm?: "osm_offline";
  threshold?: 900;
};

export type HybridConfig = {
  time_limit_seconds: 900;
  endpoint_offset_limit_m: number;
  initial_direction_count: number;
  analysis_half_width_m: number;
  initial_probe_distances_m: Array<number>;
  max_exploration_radius_m: number;
  boundary_tolerance_m: number;
  max_refinement_depth: number;
  max_baidu_requests: number;
  max_direction_count: number;
  angular_refinement_threshold_m: number;
  angular_refinement_ratio: number;
  topology_risk_threshold: number;
  topology_search_radius_m: number;
  max_triangle_edge_m: number;
  mixed_triangle_target_m: number;
  request_qps: number;
  deadline_seconds: number;
  failure_streak_limit: number;
  origin_endpoint_failure_streak_limit: number;
  interior_gap_radii_m: Array<number>;
  bridge_display_width_m: number;
};

export type HybridRequest = {
  origin: Origin;
  coordinate_system: "bd09ll";
  config?: Partial<HybridConfig>;
  client_request_id: string;
};

export type HybridIsochrone = {
  algorithm: "hybrid";
  algorithm_version: string;
  coordinate_system: "bd09ll";
  quality: "usable" | "partial" | "insufficient";
  coverage_policy: "continuous_land_interior";
  geometry: Geometry | null;
  displayGeometry?: Geometry | null;
  evidence_geometry: Geometry | null;
  inferred_fill_geometry: Geometry | null;
  unknown_region: Geometry | null;
  evidence_unknown_region: Geometry | null;
  computation_extent: Geometry;
  extent_truncated: boolean;
  requests_used: number;
  valid_baidu_samples: number;
  invalid_baidu_samples: number;
  unknown_samples: number;
  boundary_error_estimate: number | null;
  stop_reason: string;
  warnings: Array<string>;
  config: HybridConfig;
  readiness: HybridReadiness;
  timing_seconds: HybridTimings;
};

export type HybridReadiness = {
  mode: "full" | "degraded";
  graph_available: boolean;
  data_version_matches: boolean;
  coverage_available: boolean;
  origin_in_coverage: boolean;
  extent_in_coverage: boolean;
  obstacle_layer_available: boolean;
  risk_layer_available: boolean;
  warnings: Array<string>;
};

export type HybridTimings = {
  preparation: number;
  obstacle_load: number;
  requests: number;
  geometry_rebuilds: number;
  compute_total: number;
  task_total: number;
};

export type HybridResultResponse = {
  schema_version: "1.0";
  responseType: "result";
  taskId: string;
  taskStatus: "completed";
  status: "complete" | "partial" | "failed" | "empty";
  businessStatus: "complete" | "partial" | "failed" | "empty";
  dataSource: "synthetic" | "baidu_walking";
  center: Origin;
  generatedAt: number;
  facilitiesStatus: "not_integrated" | "complete" | "partial" | "failed";
  facilityAnalysis: FacilityAnalysis | null;
  coordinateSystem: "bd09ll";
  coordinateOrder: "longitude,latitude";
  units: Record<string, string>;
  rules: Rules;
  data: Data;
  algorithm: HybridIsochrone;
  warnings: Array<Issue>;
  errors: Array<Issue>;
  isochrone: HybridIsochrone;
  config_hash: string;
  result_hash: string;
};

export type HybridError = {
  code: string;
  message: string;
};
